name: aerium
description: A beautifully crafted portfolio site built with flutter

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  bubble_tab_indicator: ^0.1.6
  dots_indicator: ^2.1.0
  flutter_otp_text_field: ^1.1.0

  auto_route: ^9.0.0

  # auto_route: ^4.2.0


  google_fonts: ^6.2.1
  responsive_builder: ^0.7.1
  font_awesome_flutter: ^10.8.0 
  url_launcher: ^6.0.9
  flutter_feather_icons: ^2.0.0+1 
  animated_text_kit: ^4.2.1
  visibility_detector: ^0.4.0+2
  flutter_bloc: ^8.1.6
  layout: ^1.0.5
  freezed_annotation: ^2.4.4  
  dartz: ^0.10.0
  get_it: ^8.0.3
  flutter_spinkit: ^5.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  ffi: ^2.1.3
  win32: ^5.9.0
  
  gap: ^3.0.1
  carousel_slider: ^5.0.0
  just_audio: ^0.9.42
  audioplayers: ^6.1.0
  another_carousel_pro: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_launcher_icons: "^0.9.3"
  build_runner:
  freezed: ^2.5.7
  functional_widget: ^0.10.0
  auto_route_generator: ^9.0.0
  # auto_route_generator: ^4.2.0


flutter_icons:
  image_path: "assets/images/drop_icon.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/audio/
    - assets/images/
    - assets/images/projects/
    - assets/images/projects/aerium-v1/
    - assets/images/projects/aerium-v2/
    - assets/images/projects/disneyplus/
    - assets/images/projects/drop/
    - assets/images/projects/flutter_catalog/
    - assets/images/projects/foodybite/
    - assets/images/projects/login_catalog/
    - assets/images/projects/nimbus/
    - assets/images/projects/otp_package/
    - assets/images/projects/roam/
    - assets/images/projects/outfitr/
    - assets/images/products/
  #    - assets/screenshots/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: sofia_pro
      fonts:
        - asset: assets/fonts/sofia_pro/Sofia Pro ExtraLight Italic Az.otf
          weight: 100
        - asset: assets/fonts/sofia_pro/Sofia Pro ExtraLight Az.otf
          weight: 200
        - asset: assets/fonts/sofia_pro/Sofia Pro Light Az.otf
          weight: 300
        - asset: assets/fonts/sofia_pro/Sofia Pro Regular Italic Az.otf
          weight: 400
        - asset: assets/fonts/sofia_pro/Sofia Pro Medium Italic Az.otf
          weight: 500
        - asset: assets/fonts/sofia_pro/Sofia Pro Bold Az.otf
          weight: 700
        - asset: assets/fonts/sofia_pro/Sofia Pro Black Az.otf
          weight: 800
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
